aira:
  gaiah:
    repo:
      repo_name: "AIRA-Sample03"
      description: ""
      private: True
    local:
      repo_dir: "C:/Prj/AIRA-Sample03"
      no_initial_commit: false
    commit:
      commit_msg_path: ".aira/aira.Gaiah.md"

  llm:
    model: "gemini/gemini-1.5-pro-latest"

  repository_summary_output_dir: .aira
  readme_prompt_template_path: .aira/readme_prompt_template.txt
  
  harmon_ai:
    environment:
      repo_name: "AIRA-Sample03"
      owner_name: "Sunwood-ai-labs"
      package_name: "AIRA"
      icon_url: "https://huggingface.co/datasets/MakiAi/IconAssets/resolve/main/AIRA_SAMPLE2.png"
      title: "AIRA Sample01"
      subtitle: "～AI-Integrated Repository for Accelerated Development～"
      website_url: "https://hamaruki.com/"
      github_url: "https://github.com/Sunwood-ai-labs"
      twitter_url: "https://x.com/hAru_mAki_ch"
      blog_url: "https://hamaruki.com/"

    product:
      important_message_file: "important_template.md"
      sections_content_file: "sections_template.md"
      output_file: "README_template.md"
      cicd_file_path: "publish-to-pypi.yml"
      cicd_main_path: "publish-to-pypi.yml"
      github_cicd_dir: ".github/workflows"
    
    llm_product:
      sections_content_file: "sections_template_llm.md"

    development:
      output_dir: "C:/Prj/AIRA/.harmon_ai"

    main:
      main_dir: "C:/Prj/AIRA/"
      replace_readme: true

    instructions_prompt: .aira/instructions.md
