gaiah:
  repo:
    create_repo: true
    repo_name: "AIRA-Sample00"
    description: ""
    private: false

  local:
    init_repo: true
    repo_dir: "C:/Prj/AIRA-Sample/AIRA-Sample00"
    no_initial_commit: false

  commit:
    process_commits: true
    commit_msg_path: "C:/Prj/AIRA-Sample/.Gaiah.md"
    branch_name: null